### ISSUE TITLE
Search bar on Diversity Page not working (Major bug)

### ISSUE THREAD

**Issue by syd-moral** [info442-su23/e-team#86]
Summary: When clicking on the search bar, nothing happens.
Environment: MacOS Chrome latest version
Steps: Click on diversity tab, deselect 'art' on search bar, select search bar.
Expected Result: Able to type into search bar
Actual result: Unable to interact with search bar

**Comment by VictoriaVVei** [comment]
Our “what type is being search" is not for searching. It is used for show what tag is being filter from main page, instead of input. 

We provide a video: 
https://drive.google.com/file/d/1UlBG3jXRU6_OJPTEvoO5GphT1LB1IbzE/view?usp=sharing

![1A15A521-E1F4-4C8B-B5B5-A22C554F7D30](https://github.com/info442-su23/e-team/assets/91993339/40e5468d-e839-447e-8d1f-908ff1662ef8)
![72BBCC4E-040F-41E0-BA8B-8A29478701CD](https://github.com/info442-su23/e-team/assets/91993339/7e6379e3-5352-4e70-8d23-40868265751c)
