### ISSUE TITLE
Search bar is not bringing up search results for existing art (Major)

### ISSUE THREAD

**Issue by bonglrob** [info442-su23/e-team#89]
Expected: Pop art search result to appear
Actual: Nothing found

Env: Brave Browser/Chrome v1.56.20, Acer Windows 11

![brave_ofkFCvYXV6](https://github.com/info442-su23/e-team/assets/8757841/0592b0d9-8e20-4b73-8802-9928cdc2694c)
![brave_CcPmRTv7tQ](https://github.com/info442-su23/e-team/assets/8757841/1d13062d-8062-4700-bf2b-54997d97d59d)

**Comment by VictoriaVVei** [comment]
We ment to design in this way. You need to input a few more character to specify a range of posts. We done in this way because to reduce the data reading (firebase has reading limited). If we have a lot of posts and parts of them include pop art, it will cause huge reading which we do not expected.
![3D303B2B-54E4-4929-AB63-82EF0630EA54](https://github.com/info442-su23/e-team/assets/91993339/5197c5f1-ed49-43ee-b08b-7b182aa027b0)

We increase the threshold value on purpose.
![C082755D-F36C-4E00-A1B4-0047A1B6B1CD](https://github.com/info442-su23/e-team/assets/91993339/c0ff1243-4a28-4996-b6ec-67ffec8a3009)
![201181A8-6B77-447B-9B63-805D200279F8](https://github.com/info442-su23/e-team/assets/91993339/e145f966-75cb-43a4-b4cc-79288ac72ccd)
